openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "8090"
paths:
  /risk:
    post:
      operationId: postRisk
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiskRequest'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskResponse'
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    RiskRequest:
      required:
      - ip
      type: object
      properties:
        ip:
          type: string
    RiskResponse:
      required:
      - hasRisk
      type: object
      properties:
        hasRisk:
          type: boolean
